name: ci

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - name: Sync Environment
      run: uv sync --frozen
    - name: Lint
      run: make lint
    - name: Format
      run: make check-format

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4
    - name: Setup uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}
    - name: Sync Environment
      run: uv sync --frozen
    - name: Test
      run: make test
    - name: Type check
      run: make type-check

# vim: sw=2
