name: ci

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make requirements
    - name: Lint
      run: |
        make lint
    - name: Format
      run: |
        make format && git diff --quiet HEAD

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - if: ${{ matrix.python-version == 3.5 }}
      run: |
        sed -i '/^black/d' requirements-test.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make requirements
    - name: Test
      run: |
          make test

# vim: sw=2
