name: weekly

on:
  schedule:
    - cron: 11 4 * * 0

jobs:
  weekly:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11-dev", "3.12-dev"]

    steps:
    - uses: actions/checkout@v4
    - name: Setup uv
    - uses: actions/setup-uv@v5
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}
    - name: Sync Environment
      run: uv sync --frozen
    - name: Test
      run: make test
    - name: Type check
      run: make type-check

# vim: sw=2
