name: weekly

on:
  schedule:
    - cron: 11 4 * * 0

jobs:
  weekly:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11-dev", "3.12-dev"]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make requirements
    - name: Lint
      run: |
        make lint
    - name: Format
      run: |
        make format && git diff --quiet HEAD
    - name: Type check
      run: |
        make type-check
    - name: Test
      run: |
          make test

# vim: sw=2
